// frontend-angular/src/app/chat/chat.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatListModule } from '@angular/material/list';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { TextFieldModule } from '@angular/cdk/text-field';
import { ChatService, Message, ChatSession } from './chat.service';
import { MessageComponent } from './message.component';
import { ThemeService } from '../shared/theme.service';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatSidenavModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatSlideToggleModule,
    TextFieldModule,
    MessageComponent
  ],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.scss'
})
export class ChatComponent implements OnInit, OnDestroy {
  private chatService = inject(ChatService);
  private themeService = inject(ThemeService);
  private fb = inject(FormBuilder);

  @ViewChild('messagesContainer') messagesContainer!: ElementRef;
  @ViewChild('fileInput') fileInput!: ElementRef;

  messageForm: FormGroup;
  messages: Message[] = [];
  sessions: ChatSession[] = [];
  currentSession: ChatSession | null = null;
  isLoading = false;
  selectedFile: File | null = null;
  isDarkMode = false;
  isSidebarOpen = true;

  private destroy$ = new Subject<void>();

  constructor() {
    this.messageForm = this.fb.group({
      content: ['']
    });
  }

  ngOnInit(): void {
    // Show welcome message with sample questions
    this.showWelcomeMessage();

    // Subscribe to messages
    this.chatService.messages$
      .pipe(takeUntil(this.destroy$))
      .subscribe(messages => {
        this.messages = messages;
        setTimeout(() => this.scrollToBottom(), 100);
      });

    // Subscribe to sessions
    this.chatService.sessions$
      .pipe(takeUntil(this.destroy$))
      .subscribe(sessions => {
        this.sessions = sessions;
      });

    // Subscribe to current session
    this.chatService.currentSession$
      .pipe(takeUntil(this.destroy$))
      .subscribe(session => {
        this.currentSession = session;
      });

    // Subscribe to loading state
    this.chatService.isLoading$
      .pipe(takeUntil(this.destroy$))
      .subscribe(isLoading => {
        this.isLoading = isLoading;
      });

    // Subscribe to theme
    this.themeService.isDarkMode$
      .pipe(takeUntil(this.destroy$))
      .subscribe(isDark => {
        this.isDarkMode = isDark;
      });

    // Check window size for sidebar
    this.checkWindowSize();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  onSubmit(): void {
    if (!this.isLoading) {
      const content = this.messageForm.value.content?.trim() || '';

      // Allow submission if either content exists OR a file is selected
      if (!content && !this.selectedFile) return;

      const request = {
        content: content || 'Process uploaded file',
        session_id: this.currentSession?.id,
        file: this.selectedFile || undefined
      };

      // Clear the form immediately for better UX
      this.messageForm.reset();
      this.selectedFile = null;

      this.chatService.sendMessage(request).subscribe({
        next: () => {
          // Form already cleared above
        },
        error: (error) => {
          console.error('Error sending message:', error);
          // Optionally restore the message on error
          // this.messageForm.patchValue({ content });
        }
      });
    }
  }

  onEnterKey(event: KeyboardEvent): void {
    if (!event.shiftKey) {
      event.preventDefault();
      this.onSubmit();
    }
  }

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];
    }
  }

  removeFile(): void {
    this.selectedFile = null;
    if (this.fileInput) {
      this.fileInput.nativeElement.value = '';
    }
  }

  triggerFileInput(): void {
    this.fileInput.nativeElement.click();
  }

  newChat(): void {
    this.chatService.createNewSession();
  }

  loadSession(session: ChatSession): void {
    this.chatService.loadSession(session.id).subscribe();
    if (window.innerWidth < 768) {
      this.isSidebarOpen = false;
    }
  }

  deleteSession(event: Event, session: ChatSession): void {
    event.stopPropagation();
    if (confirm('Are you sure you want to delete this conversation?')) {
      this.chatService.deleteSession(session.id).subscribe();
    }
  }

  toggleTheme(): void {
    this.themeService.toggleTheme();
  }

  toggleSidebar(): void {
    this.isSidebarOpen = !this.isSidebarOpen;
  }

  private scrollToBottom(): void {
    try {
      if (this.messagesContainer) {
        const element = this.messagesContainer.nativeElement;
        element.scrollTop = element.scrollHeight;
      }
    } catch (err) {
      console.error('Error scrolling to bottom:', err);
    }
  }

  private checkWindowSize(): void {
    if (window.innerWidth < 768) {
      this.isSidebarOpen = false;
    }
  }

  private showWelcomeMessage(): void {
    const welcomeMessage = {
      id: 'welcome',
      content: `# Welcome to Interface Wizard! 👋

I'm your AI assistant for healthcare data integration. I can help you with HL7/FHIR operations using natural language.

**Here are some things you can ask me:**

- "Create a test patient named John Doe"
- "Create 10 patients with random data"
- "Create a patient with diabetes diagnosis"
- "Generate ADT message for patient admission"
- "Retrieve patient with MRN 12345"
- "Send HL7 observation result for patient"

**Features:**
- Natural language patient record creation
- HL7 v2.x message generation (ADT, ORU, QRY)
- FHIR R4 resource management
- Mirth Connect integration
- OpenEMR database interaction

Just type your request below and I'll help you!`,
      role: 'assistant' as const,
      timestamp: new Date()
    };

    this.messages = [welcomeMessage];
  }

  formatDate(date: Date): string {
    const now = new Date();
    const messageDate = new Date(date);
    const diffMs = now.getTime() - messageDate.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;

    return messageDate.toLocaleDateString();
  }

  getSessionTitle(session: ChatSession): string {
    return session.title || 'New conversation';
  }
}

<div class="chat-container">
  <!-- Sidebar -->
  <mat-sidenav-container class="sidenav-container">
    <mat-sidenav
      #sidenav
      mode="side"
      [opened]="isSidebarOpen"
      class="sidebar">
      <div class="sidebar-content">
        <div class="sidebar-header">
          <button mat-raised-button color="primary" class="new-chat-button" (click)="newChat()">
            <mat-icon>add</mat-icon>
            New Chat
          </button>
        </div>

        <div class="sidebar-sessions">
          <mat-nav-list>
            <mat-list-item
              *ngFor="let session of sessions"
              [class.active]="currentSession?.id === session.id"
              (click)="loadSession(session)">
              <div class="session-item">
                <mat-icon matListItemIcon>chat_bubble_outline</mat-icon>
                <div class="session-info">
                  <span class="session-title">{{ getSessionTitle(session) }}</span>
                  <span class="session-date">{{ formatDate(session.updated_at) }}</span>
                </div>
                <button
                  mat-icon-button
                  class="delete-button"
                  (click)="deleteSession($event, session)"
                  matTooltip="Delete conversation">
                  <mat-icon>delete_outline</mat-icon>
                </button>
              </div>
            </mat-list-item>
          </mat-nav-list>

          <div class="no-sessions" *ngIf="sessions.length === 0">
            <mat-icon>chat</mat-icon>
            <p>No conversations yet</p>
            <span>Start a new chat to begin</span>
          </div>
        </div>

        <div class="sidebar-footer">
          <div class="theme-toggle">
            <mat-icon>{{ isDarkMode ? 'dark_mode' : 'light_mode' }}</mat-icon>
            <mat-slide-toggle
              [checked]="isDarkMode"
              (change)="toggleTheme()"
              color="primary">
              {{ isDarkMode ? 'Dark' : 'Light' }} Mode
            </mat-slide-toggle>
          </div>
        </div>
      </div>
    </mat-sidenav>

    <!-- Main Content -->
    <mat-sidenav-content class="main-content">
      <!-- Header -->
      <div class="chat-header">
        <button mat-icon-button (click)="toggleSidebar()" class="menu-button">
          <mat-icon>menu</mat-icon>
        </button>
        <h1>{{ currentSession ? getSessionTitle(currentSession) : 'New Conversation' }}</h1>
        <div class="spacer"></div>
      </div>

      <!-- Messages -->
      <div class="messages-container" #messagesContainer>
        <div class="messages-wrapper">
          <div class="empty-state" *ngIf="messages.length === 0">
            <div class="empty-icon">
              <svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="80" height="80" rx="16" fill="url(#emptyGradient)"/>
                <path d="M40 20L56 30V50L40 60L24 50V30L40 20Z" fill="white" opacity="0.9"/>
                <defs>
                  <linearGradient id="emptyGradient" x1="0" y1="0" x2="80" y2="80" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#667eea"/>
                    <stop offset="1" stop-color="#764ba2"/>
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <h2>How can I help you today?</h2>
            <p>Start a conversation by typing a message below</p>

            <div class="suggestions">
              <button mat-stroked-button class="suggestion-card" (click)="messageForm.patchValue({content: 'Create a test patient named John Doe'})">
                <mat-icon>person_add</mat-icon>
                <span>Create test patient</span>
              </button>
              <button mat-stroked-button class="suggestion-card" (click)="messageForm.patchValue({content: 'Create a patient with diabetes diagnosis'})">
                <mat-icon>medical_services</mat-icon>
                <span>Create patient with diagnosis</span>
              </button>
              <button mat-stroked-button class="suggestion-card" (click)="messageForm.patchValue({content: 'Generate ADT message for patient admission'})">
                <mat-icon>send</mat-icon>
                <span>Generate HL7 ADT message</span>
              </button>
              <button mat-stroked-button class="suggestion-card" (click)="messageForm.patchValue({content: 'Create 10 patients with random data'})">
                <mat-icon>group_add</mat-icon>
                <span>Create multiple patients</span>
              </button>
            </div>
          </div>

          <div class="messages-list" *ngIf="messages.length > 0">
            <app-message *ngFor="let message of messages" [message]="message"></app-message>
          </div>

          <div class="loading-indicator" *ngIf="isLoading">
            <div class="typing-animation">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        </div>
      </div>

      <!-- Input Area -->
      <div class="input-container">
        <div class="input-wrapper">
          <form [formGroup]="messageForm" (ngSubmit)="onSubmit()" class="message-form">
            <div class="file-preview" *ngIf="selectedFile">
              <mat-icon>attach_file</mat-icon>
              <span>{{ selectedFile.name }}</span>
              <button mat-icon-button type="button" (click)="removeFile()">
                <mat-icon>close</mat-icon>
              </button>
            </div>

            <div class="input-row">
              <input
                type="file"
                #fileInput
                (change)="onFileSelected($event)"
                style="display: none"
                accept=".csv,.xlsx,.xls,.pdf">

              <mat-form-field appearance="outline" class="message-input">
                <button
                  mat-icon-button
                  matPrefix
                  type="button"
                  class="attach-button-inside"
                  (click)="triggerFileInput()"
                  matTooltip="Attach CSV, Excel, or PDF file">
                  <mat-icon>attach_file</mat-icon>
                </button>

                <textarea
                  matInput
                  formControlName="content"
                  placeholder="Type your message..."
                  rows="1"
                  (keydown.enter)="onEnterKey($any($event))"
                  cdkTextareaAutosize
                  cdkAutosizeMinRows="1"
                  cdkAutosizeMaxRows="5"></textarea>
              </mat-form-field>

              <button
                mat-fab
                color="primary"
                type="submit"
                class="send-button"
                [disabled]="messageForm.invalid || isLoading"
                matTooltip="Send message">
                <mat-icon>send</mat-icon>
              </button>
            </div>
          </form>

          <div class="input-footer">
            <p>Press Enter to send, Shift + Enter for new line</p>
          </div>
        </div>
      </div>
    </mat-sidenav-content>
  </mat-sidenav-container>
</div>

// frontend-react/src/pages/Chat.tsx
import React, { useState, useEffect, useRef } from 'react';
import Sidebar from '../components/Sidebar';
import MessageBubble from '../components/MessageBubble';
import ChatInputComponent from '../components/ChatInputComponent';
import { apiService } from '../services/api';
import './Chat.css';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  created_at: string;
}

interface Session {
  id: string;
  title?: string;
  updated_at: string;
  messages?: Message[];
}

const Chat: React.FC = () => {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [currentSession, setCurrentSession] = useState<Session | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Show welcome message
    showWelcomeMessage();
    loadSessions();
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const showWelcomeMessage = () => {
    const welcomeMessage: Message = {
      id: 'welcome',
      role: 'assistant',
      content: `# Welcome to Interface Wizard! 👋

I'm your AI assistant for healthcare data integration. I can help you with HL7/FHIR operations using natural language.

**Here are some things you can ask me:**

- "Create a test patient named John Doe"
- "Create 10 patients with random data"
- "Create a patient with diabetes diagnosis"
- "Generate ADT message for patient admission"
- "Retrieve patient with MRN 12345"
- "Send HL7 observation result for patient"

**Features:**
- Natural language patient record creation
- HL7 v2.x message generation (ADT, ORU, QRY)
- FHIR R4 resource management
- Mirth Connect integration
- OpenEMR database interaction

Just type your request below and I'll help you!`,
      created_at: new Date().toISOString()
    };

    setMessages([welcomeMessage]);
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const loadSessions = async () => {
    try {
      const sessionsData = await apiService.getSessions();
      setSessions(sessionsData);
      if (sessionsData.length > 0 && !currentSession) {
        await loadSession(sessionsData[0]);
      }
    } catch (error) {
      console.error('Failed to load sessions:', error);
    }
  };

  const loadSession = async (session: Session) => {
    try {
      setCurrentSession(session);
      const messagesData = await apiService.getMessages(session.id);
      setMessages(messagesData);
    } catch (error) {
      console.error('Failed to load messages:', error);
    }
  };

  const newChat = async () => {
    try {
      const newSession = await apiService.createSession();
      setSessions([newSession, ...sessions]);
      setCurrentSession(newSession);
      setMessages([]);
    } catch (error) {
      console.error('Failed to create session:', error);
    }
  };

  const deleteSession = async (sessionId: string) => {
    try {
      await apiService.deleteSession(sessionId);
      setSessions(sessions.filter((s) => s.id !== sessionId));
      if (currentSession?.id === sessionId) {
        setCurrentSession(null);
        setMessages([]);
        if (sessions.length > 1) {
          const nextSession = sessions.find((s) => s.id !== sessionId);
          if (nextSession) {
            await loadSession(nextSession);
          }
        }
      }
    } catch (error) {
      console.error('Failed to delete session:', error);
    }
  };

  const sendMessage = async (content: string, file?: File) => {
    if (!content.trim() && !file) return;

    // Add user message to UI immediately
    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: file ? `${content} [File: ${file.name}]` : content,
      created_at: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setIsLoading(true);

    try {
      // Call the actual backend endpoint with file support
      const response = await apiService.processCommand({
        command: content || 'Process uploaded file',
        session_id: currentSession?.id || `session-${Date.now()}`
      }, file);

      // Add assistant response
      const assistantMessage: Message = {
        id: response.operation_id || Date.now().toString(),
        role: 'assistant',
        content: response.message || 'No response',
        created_at: response.created_at || new Date().toISOString(),
      };
      setMessages((prev) => [...prev, assistantMessage]);
    } catch (error: any) {
      console.error('Failed to send message:', error);
      // Add error message
      const errorMessage: Message = {
        id: Date.now().toString(),
        role: 'assistant',
        content: `Error: ${error.message || 'Failed to connect to backend. Please make sure the backend server is running on http://localhost:8000'}`,
        created_at: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  const getSessionTitle = (session: Session) => {
    if (session.title) {
      return session.title;
    }
    if (session.messages && session.messages.length > 0) {
      const firstUserMessage = session.messages.find((m) => m.role === 'user');
      if (firstUserMessage) {
        return firstUserMessage.content.substring(0, 50) + '...';
      }
    }
    return 'New Conversation';
  };

  return (
    <div className="chat-container-main">
      {isSidebarOpen && (
        <Sidebar
          sessions={sessions}
          currentSessionId={currentSession?.id || null}
          onNewChat={newChat}
          onLoadSession={loadSession}
          onDeleteSession={deleteSession}
        />
      )}

      <div className="main-content-chat">
        <div className="chat-header">
          <button className="menu-button" onClick={toggleSidebar}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <h1>{currentSession ? getSessionTitle(currentSession) : 'New Conversation'}</h1>
        </div>

        <div className="messages-container-chat">
          <div className="messages-wrapper-chat">
            {messages.length === 0 ? (
              <div className="empty-state">
                <div className="empty-icon">
                  <svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect width="80" height="80" rx="16" fill="url(#emptyGradient)" />
                    <path d="M40 20L56 30V50L40 60L24 50V30L40 20Z" fill="white" opacity="0.9" />
                    <defs>
                      <linearGradient id="emptyGradient" x1="0" y1="0" x2="80" y2="80" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#667eea" />
                        <stop offset="1" stopColor="#764ba2" />
                      </linearGradient>
                    </defs>
                  </svg>
                </div>
                <h2>How can I help you today?</h2>
                <p>Start a conversation by typing a message below</p>

                <div className="suggestions">
                  <button className="suggestion-card" onClick={() => sendMessage('Create a test patient named John Doe')}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
                    </svg>
                    <span>Create test patient</span>
                  </button>
                  <button className="suggestion-card" onClick={() => sendMessage('Create a patient with diabetes diagnosis')}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                    </svg>
                    <span>Create patient with diagnosis</span>
                  </button>
                  <button className="suggestion-card" onClick={() => sendMessage('Generate ADT message for patient admission')}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" />
                    </svg>
                    <span>Generate HL7 ADT message</span>
                  </button>
                  <button className="suggestion-card" onClick={() => sendMessage('Create 10 patients with random data')}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                    <span>Create multiple patients</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="messages-list">
                {messages.map((message) => (
                  <MessageBubble key={message.id} message={message} />
                ))}
              </div>
            )}

            {isLoading && (
              <div className="loading-indicator">
                <div className="typing-animation">
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>
        </div>

        <ChatInputComponent
          onSendMessage={sendMessage}
          disabled={false}
          isLoading={isLoading}
        />
      </div>
    </div>
  );
};

export default Chat;
